### ISSUE TITLE
Multiple Wink-Relays

### ISSUE THREAD

**Issue by thatkide** [mjg59/wink-relay-handler#1]
Nice work on this new handler.  I have 4 wink Relays and I wanted to know if the MQTT name they present are unique?  Also do you know if it's possible to add a username/password entry for the MQTT broker?

**Comment by mjg59** [comment]
Oh, the name they present isn't unique. Let me add support for that to the config as well.

**Comment by mjg59** [comment]
Ok added support for that to the config file. Thanks!

**Comment by mjg59** [comment]
Ah, bother, just realised that I changed the client ID but really need to change the actual topic names. I'll add support for that in the morning.

**Comment by mjg59** [comment]
Ok, fixed that too. The topic_prefix config option is probably what you want.

**Comment by thatkide** [comment]
Yup that was it.  The config file works great and because the wink software doesn't auto load I can have imperihome launch startup.  Thanks again, you've brought new life to this device.

**Comment by thatkide** [comment]
Ok After getting just about everything setup the only issue I'm having is activating the relays.  I publish a message to my subject prefix which on one setup is kitchen/relays/upper and kitchen/relays/lower but the relays don't change.  I'm using mosquitto broker and I see the publish out to the device but no relays activate.  If I reboot the Wink Relay the relays/upper_state and relays_lower_state update to so they are on.  Maybe I'm not sending the correct message to the relay topic?  All other topics from the Wink Relay work just fine.

**Comment by mjg59** [comment]
Hm, let me take a look - I don't use the relay functionality myself, so I could definitely have broken it.

**Comment by mjg59** [comment]
Ok this was a bug in the core MQTT client code. I've worked around it for now - latest git should work correctly. Thanks for your patience!

**Comment by thatkide** [comment]
Thanks I'll give it a try later tonight.  No problem on the wait, It gave me a chance to learn more about coding.

**Comment by Squirmy18** [comment]
Im having the same problem. Temp & Humidity work fine. I cannot control the relays with the buttons or sending Relay1/relays/upper/0 or Relay1/relays/upper/1
When subscribing to Relay1/switches/upper  and I press the top button, it always show "on"

**Comment by mjg59** [comment]
The buttons will always send instant signals - they're buttons, not switches (with hindsight, calling it "switch" was a mistake on my part). You need to send ON or OFF to Relay1/relays/upper in order to control the relay.

**Comment by Squirmy18** [comment]
Still not working on this end. Physically pushing the button on the Wink does nothing. The light stays on. Also when pushing the button, mqtt recieves the “on” reply only & never off. Is there any other Wink software that needs to be shutdown?

**Comment by Squirmy18** [comment]
Relays are working sending ON & OFF (caps!)
Button presses still nothing. mqtt shows status of lower case “on” only. Never off.

**Comment by Squirmy18** [comment]
I've tried both of these files:
https://github.com/mjg59/wink-relay-handler/files/1459086/wink-handler.zip
https://github.com/mjg59/wink-relay-handler/releases/download/v1.0/wink-handler.zip
Both of these break the use of pressing the buttons to operate the lights.
If I restore the edisonwink to the original file, they work as expected.
Is there a cache that needs to be dumped? Is this the correct behavior the handler performs ?

**Comment by mjg59** [comment]
Yes, the button will only send an "on" message. The buttons don't have any state, they're only buttons. You need to interpret them as toggles at the broker end, not at the Wink end.

**Comment by Squirmy18** [comment]
Sounds like I have it installed properly then. If my controller ever goes down then I cannot manually turn lights on or off tho. 

Is there any way a simple code could be written to the wink to toggle the relay?
/// on Relay1#Switch do
if [Relay1#Switch]=0
gpio,15,1
else
gpio,15,0
endif
endon
///
I use that code on a WiFi esp8266 plug so I can use the built in power button. 

Without the relays working locally has an extremely poor “WAF”. (wife approval factor)

**Comment by mjg59** [comment]
I could add support in the configuration file for tying the buttons directly to the relay, but I think the only way to make that work would be to then disable the mqtt signals from the buttons. Would that be sufficient?

**Comment by thatkide** [comment]
If you could have both mqtt and local control of the relays that would be great.  I don't know if that's possible though.

**Comment by okow** [comment]
In my opinion it would make sense to make the local reaction controllable by a configuration option but leave the signaling as it is (in both cases).
Since other members of the system also get the upper/lower_state they always are able to know the state but might also be interested in the actual key-press.

if [key-pressed]
--> send switches/[switch]
--> if [option local-toggle]
---- --> toggle [relay] & send [relay_state]

**Comment by mjg59** [comment]
Can you try with this file [wink-handler.zip](https://github.com/mjg59/wink-relay-handler/files/1565165/wink-handler.zip) and put switch_toggle=true in the config file? You can put send_switch=false to disable sending the MQTT events.

**Comment by okow** [comment]
Seems to work as intended.
The local toggle is controllable by the config-option as is the sending of the pressed-info.
I also switched off both, then the relays are only controllable remote and button-presses are ignored.

**Comment by rs1932** [comment]
The handler works great, thank you for making the wink useful! One question though, if the MQTT server becomes inaccessible even for a few seconds the relay seems to lose connectivity to the server, at that stage not able to receive any messages from the relay nor send any messages to the relay. The relay though is connected and working, I am able to adb into the relay and upon killing the wink-handler process it starts working again. Is the MQTT reconnect timing out and should it not continue searching for the server?
Thanks

**Comment by mjg59** [comment]
@rs1932 Could you open a separate issue for that?

**Comment by rs1932** [comment]
Created a new issue for the MQTT server connectivity.

On the above topic of this thread if it is not too much trouble would it be possible to have separate switch1_toggle and switch2_toggle and send_switch1 and send_switch2  configuration parameters in the config file? I would then be able to control behavior of each switch individually. Would make it extremely versatile.

Thanks!.
